replicaCount: 1

image:
  repository: 723915311050.dkr.ecr.us-east-1.amazonaws.com/go
  pullPolicy: IfNotPresent
  tag: "1.2.1"

serviceAccount:
  create: false

service:
  type: LoadBalancer
  port: 8080

serviceAnnotations: 
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-036b65f09bf122375"

ingress:
  enabled: false

resources:
   limits:
     cpu: 100m
     memory: 128Mi
   requests:
     cpu: 100m
     memory: 128Mi

env:
  API_KEY: a6311858fb35df63b55216bae4aa952a